# GoReleaser v2 configuration for git-herd
# https://goreleaser.com/customization/

version: 2

project_name: git-herd

before:
  hooks:
    # Clean up and test before building
    - go mod tidy
    - go generate ./...
    - go test -race ./...
    - make clean

builds:
  - id: git-herd
    main: ./cmd/git-herd
    binary: git-herd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Remove 386 and arm32 - less common in 2025
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: git-herd
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yaml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📝 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🔧 Other"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^ci:"
      - "^build:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge branch
      - go mod tidy

# GitHub release configuration
release:
  github:
    owner: entro314-labs
    name: git-herd
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## git-herd {{ .Tag }}

    Welcome to this new release of git-herd!

    **Full Changelog**: https://github.com/entro314-labs/git-herd/compare/{{ .PreviousTag }}...{{ .Tag }}

  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install entro314-labs/tap/git-herd
    ```

    ### Winget (Windows)
    ```bash
    winget install git-herd
    ```

    ### AUR (Arch Linux)
    ```bash
    yay -S git-herd
    ```

    ### Manual Installation
    Download the appropriate binary for your platform from the assets below.

# Docker image configuration
dockers:
  - id: git-herd
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/entro314-labs/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/entro314-labs/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/entro314-labs/git-herd"
      - "--platform=linux/amd64"

# SBOM generation for supply chain security (optional - requires syft installation)
# sboms:
#   - artifacts: archive
#     documents:
#       - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

# Homebrew tap automation
brews:
  - name: git-herd
    repository:
      owner: entro314-labs
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/entro314-labs/git-herd
    description: "A concurrent Git repository management tool"
    license: "MIT"
    directory: Formula
    test: |
      system "#{bin}/git-herd", "--version"
    install: |
      bin.install "git-herd"

# Linux packages (deb/rpm)
nfpms:
  - id: git-herd
    package_name: git-herd
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/entro314-labs/git-herd
    description: A concurrent Git repository management tool written in Go
    maintainer: entro314-labs <noreply@github.com>
    license: MIT
    vendor: entro314-labs
    formats:
      - deb
      - rpm
    contents:
      - src: config.yaml
        dst: /etc/git-herd/git-herd.yaml
        type: config|noreplace
    dependencies:
      - git

# Announcements (optional - uncomment to enable)
# announce:
#   discord:
#     enabled: true
#     message_template: 'git-herd {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'
#   slack:
#     enabled: true
#     message_template: 'git-herd {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'